version: '3'

services:

  envoy:
    image: envoyproxy/envoy-dev:e4955aed5694f9935d674419dbb364e744f697b4
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: host

  #server:
  #  build: ./stream
  #  image: stream
  #  ports:
  #    - "50051:50051"
  #  environment:
  #    - NODE_ENV=production

  #web:
  #  build: ./web
  #  image: web
  #  ports:
  #    - "8080:8080"

